# any rubocop overrides live in here

RSpec/Capybara/FeatureMethods:
  EnabledMethods:
    - feature
    - scenario

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Max: 7
  CountAsOne:
    - heredoc
    - hash
  Exclude:
    - spec/features/**/*

RSpec/InstanceVariable:
  Exclude:
    - spec/features/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb


