# https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard

require:
  - standard
  - rubocop-performance
  - rubocop-rspec

# Use the defaults from https://github.com/testdouble/standard
inherit_gem:
  standard: config/ruby-3.2.yml

AllCops:
  TargetRubyVersion: 3.2.2
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  UseCache: true
  CacheRootDirectory: .
  MaxFilesInCache: 10000
  Exclude:
    - tmp/**/*
    - vendor/**/*

# any rubocop overrides live in here

RSpec/Capybara/FeatureMethods:
  EnabledMethods:
    - feature
    - scenario

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Max: 7
  CountAsOne:
    - heredoc
    - hash
  Exclude:
    - spec/features/**/*

RSpec/InstanceVariable:
  Exclude:
    - spec/features/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb


