name: "CI"

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: builld
        run: |
          make ci
